# Generated by Django 6.0.2 on 2026-02-15 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='minutes_to_campus',
            field=models.PositiveIntegerField(blank=True, help_text='Estimated walking time to campus in minutes', null=True),
        ),
    ]
