# Generated by Django 6.0.2 on 2026-03-26 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_hostel_minutes_to_campus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hostel',
            options={'ordering': ['-created_at']},
        ),
    ]
